"""
Solomon OS LLM Core — Adapted from GenericAgent/llmcore.py
==========================================================
Token-efficient LLM interface with context compression.
Key insight from GenericAgent: compress <thinking>/<tool_use>/<tool_result> 
tags in older messages. Target: stay under 30K tokens.
"""

import os, json, re, time, uuid
from datetime import datetime

RESP_CACHE_KEY = str(uuid.uuid4())

def load_mykeys():
    """Load API keys from Zo secrets / environment."""
    keys = {}
    # MiniMax (Zo default)
    if os.environ.get("MINIMAX_API_KEY"):
        keys["oai_minimax"] = {
            "apikey": os.environ["MINIMAX_API_KEY"],
            "apibase": "https://api.minimax.io/v1",
            "model": "MiniMax-M2.7",
        }
    # Ollama (local, free)
    if os.environ.get("OLLAMA_HOST"):
        keys["oai_ollama"] = {
            "apikey": "ollama",
            "apibase": os.environ.get("OLLAMA_HOST", "http://localhost:11434"),
            "model": os.environ.get("OLLAMA_MODEL", "qwen3:1.7b"),
        }
    return keys

mykeys = load_mykeys()

def compress_history_tags(messages, keep_recent=10, max_len=800, force=False):
    """Compress <thinking>/<tool_use>/<tool_result> in older messages to save tokens.
    GenericAgent insight: this alone cuts token usage 6x."""
    compress_history_tags._cd = getattr(compress_history_tags, '_cd', 0) + 1
    if force: compress_history_tags._cd = 0
    if compress_history_tags._cd % 5 != 0: return messages
    
    _pats = {
        tag: re.compile(rf'(<{tag}>)([\s\S]*?)(</{tag}>)')
        for tag in ('thinking', 'think', 'tool_use', 'tool_result')
    }
    _hist_pat = re.compile(r'<(history|key_info)>[\s\S]*?</\1>')
    
    def _trunc_str(s):
        if isinstance(s, str) and len(s) > max_len:
            return s[:max_len//2] + '\n...[Truncated]...\n' + s[-max_len//2:]
        return s
    
    def _trunc(text):
        text = _hist_pat.sub(lambda m: f'<{m.group(1)}>[...]</{m.group(1)}>', text)
        for pat in _pats.values():
            text = pat.sub(lambda m: m.group(1) + _trunc_str(m.group(2)) + m.group(3), text)
        return text
    
    for i, msg in enumerate(messages):
        if i >= len(messages) - keep_recent: break
        c = msg.get('content', '')
        if isinstance(c, str): msg['content'] = _trunc(c)
        elif isinstance(c, list):
            for b in c:
                if not isinstance(b, dict): continue
                t = b.get('type')
                if t == 'text' and isinstance(b.get('text'), str):
                    b['text'] = _trunc(b['text'])
                elif t == 'tool_result':
                    tc = b.get('content', '')
                    if isinstance(tc, str): b['content'] = _trunc_str(tc)
    
    return messages

def trim_messages_history(history, context_win=128000):
    """Trim history to stay within context window budget.
    Called before every LLM call to avoid overflow."""
    compress_history_tags(history)
    cost = sum(len(json.dumps(m, ensure_ascii=False)) for m in history)
    print(f"[Solomon Context] {cost} chars, {len(history)} messages in history")
    
    if cost > context_win * 3:
        compress_history_tags(history, keep_recent=4, force=True)
        target = context_win * 3 * 0.6
        while len(history) > 5 and cost > target:
            history.pop(0)
            while history and history[0].get('role') != 'user':
                history.pop(0)
            if history and history[0].get('role') == 'user':
                history[0] = dict(history[0])
                history[0]['content'] = str(history[0].get('content', ''))[:500]
    return history

# ─── SOLOMON OS SELF-EVOLUTION MECHANISM ───────────────────────────────────────
# Adapted from GenericAgent's skill crystallization concept.
# After every successful task → write a skill file to brain/skills/
# This is the "使用越久越强" (stronger the longer you use it) mechanism.

SKILLS_DIR = "/home/workspace/solomon-vault/brain/skills"

def crystallize_skill(task_name, tool_calls_made, outcome_summary, confidence=0.8):
    """Write a skill file after a successful task.
    Called by the memory system after every successful session."""
    os.makedirs(SKILLS_DIR, exist_ok=True)
    slug = re.sub(r'[^a-z0-9]+', '_', task_name.lower())[:50]
    path = f"{SKILLS_DIR}/{slug}.md"
    
    content = f"""# Skill: {task_name}

> Crystallized from real session on {datetime.now().strftime('%Y-%m-%d')}.
> Confidence: {confidence}

## What this skill does
{outcome_summary}

## Tool chain used
"""
    for tc in tool_calls_made:
        content += f"- `{tc['tool']}({', '.join(tc.get('args', {}).keys())})`\n"
    
    content += f"""
## When to use this skill
Trigger when you see: *{task_name}* or similar task patterns.

---
Auto-generated by Solomon OS GenericAgent integration. Do not edit.
"""
    with open(path, 'w') as f:
        f.write(content)
    print(f"[Solomon Skill] Crystallized: {slug}.md")
    return path

def load_skill(skill_name):
    """Load a crystallized skill file."""
    slug = re.sub(r'[^a-z0-9]+', '_', skill_name.lower())[:50]
    path = f"{SKILLS_DIR}/{slug}.md"
    if os.path.exists(path):
        with open(path) as f: return f.read()
    return None

def list_skills():
    """List all crystallized skills."""
    if not os.path.exists(SKILLS_DIR): return []
    return sorted([f[:-3] for f in os.listdir(SKILLS_DIR) if f.endswith('.md')])